# Generated by Django 5.1.1 on 2024-09-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_dt',
            new_name='created_at',
        ),
    ]
